// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/golang-micro-product.proto

package golangmicroproduct

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GolangMicroProduct service

func NewGolangMicroProductEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GolangMicroProduct service

type GolangMicroProductService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (GolangMicroProduct_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (GolangMicroProduct_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (GolangMicroProduct_BidiStreamService, error)
}

type golangMicroProductService struct {
	c    client.Client
	name string
}

func NewGolangMicroProductService(name string, c client.Client) GolangMicroProductService {
	return &golangMicroProductService{
		c:    c,
		name: name,
	}
}

func (c *golangMicroProductService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "GolangMicroProduct.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golangMicroProductService) ClientStream(ctx context.Context, opts ...client.CallOption) (GolangMicroProduct_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "GolangMicroProduct.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &golangMicroProductServiceClientStream{stream}, nil
}

type GolangMicroProduct_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type golangMicroProductServiceClientStream struct {
	stream client.Stream
}

func (x *golangMicroProductServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *golangMicroProductServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *golangMicroProductServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *golangMicroProductServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *golangMicroProductServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *golangMicroProductServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *golangMicroProductService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (GolangMicroProduct_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "GolangMicroProduct.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &golangMicroProductServiceServerStream{stream}, nil
}

type GolangMicroProduct_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type golangMicroProductServiceServerStream struct {
	stream client.Stream
}

func (x *golangMicroProductServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *golangMicroProductServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *golangMicroProductServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *golangMicroProductServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *golangMicroProductServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *golangMicroProductServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *golangMicroProductService) BidiStream(ctx context.Context, opts ...client.CallOption) (GolangMicroProduct_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "GolangMicroProduct.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &golangMicroProductServiceBidiStream{stream}, nil
}

type GolangMicroProduct_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type golangMicroProductServiceBidiStream struct {
	stream client.Stream
}

func (x *golangMicroProductServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *golangMicroProductServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *golangMicroProductServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *golangMicroProductServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *golangMicroProductServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *golangMicroProductServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *golangMicroProductServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GolangMicroProduct service

type GolangMicroProductHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, GolangMicroProduct_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, GolangMicroProduct_ServerStreamStream) error
	BidiStream(context.Context, GolangMicroProduct_BidiStreamStream) error
}

func RegisterGolangMicroProductHandler(s server.Server, hdlr GolangMicroProductHandler, opts ...server.HandlerOption) error {
	type golangMicroProduct interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type GolangMicroProduct struct {
		golangMicroProduct
	}
	h := &golangMicroProductHandler{hdlr}
	return s.Handle(s.NewHandler(&GolangMicroProduct{h}, opts...))
}

type golangMicroProductHandler struct {
	GolangMicroProductHandler
}

func (h *golangMicroProductHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.GolangMicroProductHandler.Call(ctx, in, out)
}

func (h *golangMicroProductHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.GolangMicroProductHandler.ClientStream(ctx, &golangMicroProductClientStreamStream{stream})
}

type GolangMicroProduct_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type golangMicroProductClientStreamStream struct {
	stream server.Stream
}

func (x *golangMicroProductClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *golangMicroProductClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *golangMicroProductClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *golangMicroProductClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *golangMicroProductClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *golangMicroProductHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GolangMicroProductHandler.ServerStream(ctx, m, &golangMicroProductServerStreamStream{stream})
}

type GolangMicroProduct_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type golangMicroProductServerStreamStream struct {
	stream server.Stream
}

func (x *golangMicroProductServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *golangMicroProductServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *golangMicroProductServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *golangMicroProductServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *golangMicroProductServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *golangMicroProductHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.GolangMicroProductHandler.BidiStream(ctx, &golangMicroProductBidiStreamStream{stream})
}

type GolangMicroProduct_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type golangMicroProductBidiStreamStream struct {
	stream server.Stream
}

func (x *golangMicroProductBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *golangMicroProductBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *golangMicroProductBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *golangMicroProductBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *golangMicroProductBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *golangMicroProductBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
